In [1]:
# 1. Import pandas
import pandas as pd

# 2. Create sample sales data
data = {
    'Store': ['North', 'South', 'North', 'East', 'South', 'East', 'North'],
    'Product': ['Laptop', 'Phone', 'Laptop', 'Tablet', 'Phone', 'Laptop', 'Tablet'],
    'Sales': [1200, 800, 1500, 600, 900, 1100, 700],
    'Quantity': [2, 3, 3, 1, 4, 2, 2]
}

df = pd.DataFrame(data)
print("Original Data:")
print(df)

Original Data:
   Store Product  Sales  Quantity
0  North  Laptop   1200         2
1  South   Phone    800         3
2  North  Laptop   1500         3
3   East  Tablet    600         1
4  South   Phone    900         4
5   East  Laptop   1100         2
6  North  Tablet    700         2

In [2]:
# group by store and sum all numbers column

store_summary = df.groupby('Store').sum()
print(store_summary)

                  Product  Sales  Quantity
Store
East         TabletLaptop   1700         3
North  LaptopLaptopTablet   3400         7
South          PhonePhone   1700         7

In [3]:
# group single column
sales_by_store = df.groupby('Store')['Sales'].sum()
print(sales_by_store)

Store
East     1700
North    3400
South    1700
Name: Sales, dtype: int64

In [4]:
# multiple Aggeregations (sum,mean,count)
summary = df.groupby('Store').agg({
    "Sales":['sum','mean','count'],
    "Quantity":'sum'
})
print(summary)

      Sales                    Quantity
        sum         mean count      sum
Store
East   1700   850.000000     2        3
North  3400  1133.333333     3        7
South  1700   850.000000     2        7

In [5]:
# group by multiple column
by_store_product = df.groupby(['Store','Product'])['Sales'].sum()
print(by_store_product)

Store  Product
East   Laptop     1100
       Tablet      600
North  Laptop     2700
       Tablet      700
South  Phone      1700
Name: Sales, dtype: int64

In [6]:
# Example 2

data = pd.read_csv("credit_card_transactions (1).csv")
(data.head())

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [7]:
amount_t = data.groupby('Transaction_Type')['Amount'].sum()
(amount_t)

Transaction_Type
ATM               3368427.03
Mobile Payment    3379398.75
Online            3622808.77
POS               3335966.18
Name: Amount, dtype: float64

In [8]:
merchant = data.groupby('Merchant').sum(5)
(merchant)

             Transaction_ID  Customer_ID      Amount
Merchant
Amazon             79147497      2236338  1917722.25
Apple Store        77079461      2232438  1847984.32
BestBuy            81264886      2416336  1974955.79
Netflix            79434071      2358113  1890755.93
Target             78583301      2270583  1970689.62
Uber               85565605      2427177  2046901.19
Walmart            84047429      2503763  2057591.63