In [24]:
%pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\comp\appdata\roaming\python\python314\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\comp\appdata\roaming\python\python314\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in c:\users\comp\appdata\roaming\python\python314\site-packages (from seaborn) (3.0.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\comp\appdata\roaming\python\python314\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\comp\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\comp\appdata\roaming\python\python314\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\comp\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime , timedelta

In [26]:
# 1 load dataset 
df = pd.read_csv("credit_card_transactions.csv")

In [27]:
# 2 check row 5 
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [28]:
# number of col and row
df.shape

(5500, 10)

In [29]:
# check columns name 
df.columns.tolist()

['Transaction_ID',
 'Customer_ID',
 'Transaction_Date',
 'Transaction_Type',
 'Merchant',
 'Category',
 'Amount',
 'Payment_Mode',
 'Transaction_Status',
 'Location']

In [30]:
# summary of Statistics 
df.describe(include='all')

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
count,5500.000000,5500.000000,5500,5500,5500,5500,5500.000000,5500,5500,5500
unique,NaN,NaN,230,4,7,6,NaN,4,3,4663
top,NaN,NaN,2023-01-01,Online,Uber,Groceries,NaN,PayPal,Approved,Christophermouth
freq,NaN,NaN,24,1453,833,951,NaN,1432,4698,6
mean,102749.500000,2989.954182,NaN,NaN,NaN,NaN,2492.109224,NaN,NaN,NaN
std,1587.857571,1153.928878,NaN,NaN,NaN,NaN,1444.493842,NaN,NaN,NaN
min,100000.000000,1000.000000,NaN,NaN,NaN,NaN,6.550000,NaN,NaN,NaN
25%,101374.750000,1988.000000,NaN,NaN,NaN,NaN,1236.935000,NaN,NaN,NaN
50%,102749.500000,3000.000000,NaN,NaN,NaN,NaN,2502.405000,NaN,NaN,NaN
75%,104124.250000,3990.000000,NaN,NaN,NaN,NaN,3767.957500,NaN,NaN,NaN
max,105499.000000,4998.000000,NaN,NaN,NaN,NaN,4997.490000,NaN,NaN,NaN

In [31]:
# indentify missing values 
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [32]:
# check datatype
df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date          str
Transaction_Type          str
Merchant                  str
Category                  str
Amount                float64
Payment_Mode              str
Transaction_Status        str
Location                  str
dtype: object

In [33]:
# convert Transaction_Date to date format
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'],errors='coerce')

In [34]:
# check datatype
df.dtypes

Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[us]
Transaction_Type                 str
Merchant                         str
Category                         str
Amount                       float64
Payment_Mode                     str
Transaction_Status               str
Location                         str
dtype: object

In [35]:
# add year , month , and day 
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

In [36]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [37]:
# check info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      5500 non-null   int64
 1   Customer_ID         5500 non-null   int64
 2   Transaction_Date    5500 non-null   datetime64[us]
 3   Transaction_Type    5500 non-null   str
 4   Merchant            5500 non-null   str
 5   Category            5500 non-null   str
 6   Amount              5500 non-null   float64
 7   Payment_Mode        5500 non-null   str
 8   Transaction_Status  5500 non-null   str
 9   Location            5500 non-null   str
 10  Year                5500 non-null   int32
 11  Month               5500 non-null   int32
 12  Day                 5500 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(2), str(6)
memory usage: 494.3 KB

In [38]:
# find the Transactions january 2023 
jan_23 = df[(df['Year'] == 2023)& (df['Month']==1)]
print(jan_23.head())

   Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
0          100000         4452       2023-01-01           Online  Walmart
1          100001         2775       2023-01-01              ATM  BestBuy
2          100002         2259       2023-01-01   Mobile Payment     Uber
3          100003         4545       2023-01-01           Online  BestBuy
4          100004         2137       2023-01-01              ATM   Amazon

   Category   Amount Payment_Mode Transaction_Status       Location  Year  \
0    Travel  4520.70   Debit Card           Approved      Jonesport  2023
1    Travel  1437.85   Debit Card           Approved  Port Jennifer  2023
2  Clothing  3320.52       PayPal           Approved     Port James  2023
3    Travel  2659.96   Debit Card           Approved     Hawkinston  2023
4    Travel  2517.07   Debit Card           Approved    Matthewland  2023

   Month  Day
0      1    1
1      1    1
2      1    1
3      1    1
4      1    1

In [39]:
# find the transactions with amount > 2500 transaction type = online 
online_1000 = df[(df['Amount'] > 2500) & (df['Transaction_Type']=='Online')]
# print(online_1000)

# create csv 
online_1000.to_csv('online2500.csv')

In [42]:
# 1. Total transaction amount per Category
total_per_category = df.groupby('Category')['Amount'].sum()
print(total_per_category)

# 2. Number of declined transactions per Payment_Mode
declined_counts = df[df['Transaction_Status'] == 'Declined'].groupby('Payment_Mode').size()
print(declined_counts)

# 3. Top 5 most frequent merchants
top_merchants = df['Merchant'].value_counts().head(5)
print(top_merchants)

# 4. Average transaction amount per Location
avg_per_location = df.groupby('Location')['Amount'].mean()
print(avg_per_location)

Category
Clothing         2185530.09
Dining           2402259.10
Electronics      2319437.34
Entertainment    2243778.43
Groceries        2386772.81
Travel           2168822.96
Name: Amount, dtype: float64
Payment_Mode
Credit Card    117
Debit Card     145
PayPal         135
UPI            134
dtype: int64
Merchant
Uber       833
Walmart    818
BestBuy    790
Netflix    774
Amazon     770
Name: count, dtype: int64
Location
Aaronfort       2429.860
Aaronmouth      2648.060
Aaronside        315.540
Abbottbury      1549.850
Abigailfort     3634.880
                  ...
Zacharyburgh    2430.690
Zacharyhaven     830.360
Zacharymouth    3508.690
Zacharystad     2925.135
Zavalaburgh      364.530
Name: Amount, Length: 4663, dtype: float64